const brokers={
  Deriv:["Boom 300 Index","Boom 500 Index","Boom 1000 Index","Crash 300 Index","Crash 500 Index","Crash 1000 Index","Volatility 10 Index","Volatility 25 Index","Volatility 50 Index","Volatility 75 Index","Volatility 100 Index"],
  Weltrade:["FX Vol","SFX Vol","PainX","GainX","FlipX","SwitchX","BreakX","TrendX","PlusX 1","FiboX","QuadX","MAX PainX","MAX GainX"],
  Headway:["BOOM 100","BOOM 200","CRASH 100","CRASH 200","FLAME","HW 100","STORM 200","STORM 500","VOL 10","VOL 20","VOL 80"]
};
const symbols={"Boom 300 Index":"BOOM300N","Boom 500 Index":"BOOM500","Boom 1000 Index":"BOOM1000","Crash 300 Index":"CRASH300N","Crash 500 Index":"CRASH500","Crash 1000 Index":"CRASH1000","Volatility 10 Index":"R_10","Volatility 25 Index":"R_25","Volatility 50 Index":"R_50","Volatility 75 Index":"R_75","Volatility 100 Index":"R_100"};
const $=id=>document.getElementById(id);let activeBroker="Deriv",payload=null,selected="Boom 300 Index",liveSocket=null;
const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}):"—";
const ageMinutes=iso=>(Date.now()-Date.parse(iso))/60000;
const signalClass=v=>v==="BUY"?"buy":v==="SELL"?"sell":"wait";

document.querySelectorAll(".broker-tab").forEach(button=>button.addEventListener("click",()=>selectBroker(button.dataset.broker)));
$("refreshButton").addEventListener("click",()=>loadSignals(true));
$("marketSelect").addEventListener("change",event=>{selected=event.target.value;renderSelected();connectLivePrice();});
$("copySignal").addEventListener("click",()=>copySignal());
$("shareSignal").addEventListener("click",()=>shareSignal());
document.querySelectorAll(".segmented").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".segmented").forEach(x=>x.classList.remove("active"));button.classList.add("active");}));

function selectBroker(name){activeBroker=name;document.querySelectorAll(".broker-tab").forEach(button=>{const active=button.dataset.broker===name;button.classList.toggle("active",active);button.setAttribute("aria-selected",String(active));});$("activeBroker").textContent=name;$("instrumentCount").textContent=brokers[name].length;$("scannerBroker").textContent=name;$("accountBroker").textContent=name;$("selectedBrokerLabel").textContent=`${name.toUpperCase()} · SYNTHETIC MARKET`;$("brokerMode").textContent=name==="Deriv"?"LIVE + IA":"MT5 À CONNECTER";$("brokerMode").style.color=name==="Deriv"?"var(--green)":"var(--amber)";selected=brokers[name][0];fillMarketSelect();render();connectLivePrice();}
function fillMarketSelect(){const select=$("marketSelect");select.innerHTML=brokers[activeBroker].map(name=>`<option value="${name}">${name}</option>`).join("");select.value=selected;}

async function loadSignals(manual=false){const button=$("refreshButton");if(manual){button.disabled=true;button.innerHTML="<span>↻</span> Actualisation…";}try{const res=await fetch(`./data/signals.json?t=${Date.now()}`,{cache:"no-store"});if(!res.ok)throw new Error(`HTTP ${res.status}`);payload=await res.json();}catch(error){payload={ok:false,status:"load_error",note:"Impossible de charger les résultats IA."};}finally{button.disabled=false;button.innerHTML="<span>↻</span> Actualiser les résultats";render();}}

function render(){const deriv=activeBroker==="Deriv";$("accountText").textContent=deriv?"Les analyses IA sont actives. Le trading direct reste verrouillé tant que le callback Deriv GitHub n’est pas validé.":`Le catalogue ${activeBroker} est visible, mais aucune analyse ne sera produite sans bougies MT5 officielles.`;$("scanDescription").textContent=deriv?"Bougies officielles H1/H4, moteur technique, contrôle Luna et validation Sol des meilleurs setups.":`Même moteur H1/H4 et OpenAI, mais flux MT5 ${activeBroker} requis. Aucune donnée Deriv n’est réutilisée.`;const notice=$("notice"),results=$("results");results.innerHTML="";
  if(!deriv){setMarketStatus(`${activeBroker} : MT5 requis`,"error");setAiStatus("OpenAI : en attente des données","error");notice.className="notice warning";notice.textContent=`ATTENDRE — le flux MT5 ${activeBroker} n’est pas encore connecté. Aucun faux cours et aucun faux signal ne sont générés.`;renderWaitingCards(results);renderSelected();return;}
  const fresh=payload?.ok&&payload?.status==="ai_analyzed"&&Number.isFinite(ageMinutes(payload.updated_at))&&ageMinutes(payload.updated_at)<130;setMarketStatus(payload?.markets_count?"Deriv : données H1/H4":"Deriv : en attente",payload?.markets_count?"live":"error");setAiStatus(fresh?"OpenAI : actif":payload?.status==="ai_analyzed"?"OpenAI : résultats anciens":"OpenAI : configuration requise",fresh?"live":"error");$("updatedAt").textContent=payload?.updated_at?new Date(payload.updated_at).toLocaleString("fr-FR",{dateStyle:"short",timeStyle:"short"}):"—";$("modelName").textContent=payload?.model||"Luna + Sol";
  if(!payload?.ok){notice.className="notice error";notice.textContent=payload?.note||"La première analyse GitHub n’a pas encore réussi. Vérifiez le secret OPENAI_API_KEY et le workflow.";renderWaitingCards(results);renderSelected();return;}
  notice.className=`notice ${fresh?"success":"warning"}`;notice.textContent=fresh?`${payload.markets_count} indices Deriv analysés. Seuls les setups où le moteur technique et OpenAI confirment le même sens peuvent afficher BUY/SELL.`:"Les résultats IA sont trop anciens. Aucun ordre ne doit être préparé avant une nouvelle exécution réussie.";
  const rows=Array.isArray(payload.markets)?payload.markets:[];rows.sort((a,b)=>(b.final_confidence||0)-(a.final_confidence||0)).forEach(row=>results.appendChild(resultCard(row,fresh)));renderSelected();}

function renderWaitingCards(container){brokers[activeBroker].slice(0,6).forEach(name=>{const card=document.createElement("button");card.className="result-card";card.innerHTML=`<div class="result-top"><div><h3>${name}</h3><p class="symbol">DONNÉES REQUISES</p></div><span class="signal wait">ATTENDRE</span></div><div class="result-score"><strong>—</strong><small>Confiance IA</small></div><div class="result-bar"><i style="width:0%"></i></div>`;card.onclick=()=>{selected=name;$("marketSelect").value=name;renderSelected();};container.appendChild(card);});}
function resultCard(row,fresh){const verdict=fresh?row.final_verdict:"ATTENDRE",confidence=fresh?row.final_confidence:0;const card=document.createElement("button");card.className=`result-card${row.market===selected?" selected":""}`;card.innerHTML=`<div class="result-top"><div><h3>${row.market}</h3><p class="symbol">${row.symbol} · H1/H4</p></div><span class="signal ${signalClass(verdict)}">${verdict}</span></div><div class="result-score"><strong>${confidence}%</strong><small>${row.ai_tier||"OpenAI"}</small></div><div class="result-bar"><i style="width:${confidence}%"></i></div>`;card.onclick=()=>{selected=row.market;$("marketSelect").value=selected;render();connectLivePrice();document.querySelector(".analysis-grid").scrollIntoView({behavior:"smooth",block:"start"});};return card;}

function renderSelected(){$("selectedMarket").textContent=selected;const row=activeBroker==="Deriv"&&payload?.markets?.find(item=>item.market===selected);const fresh=row&&payload?.updated_at&&ageMinutes(payload.updated_at)<130;const verdict=fresh?row.final_verdict:"ATTENDRE";const cls=signalClass(verdict);$("verdictBadge").className=`verdict-badge ${cls}`;$("verdictBadge").textContent=verdict;$("decisionOrb").className=`decision-orb ${cls}`;$("decisionOrb").querySelector("strong").textContent=verdict;$("decisionConfidence").textContent=fresh?`${row.final_confidence}% de confiance`:(activeBroker==="Deriv"?"Validation requise":"Données MT5 requises");$("decisionSummary").textContent=row?.ai_summary||(activeBroker==="Deriv"?"Sera attend une analyse OpenAI récente avant d’autoriser un BUY ou SELL.":`OpenAI analysera ${selected} seulement après réception de ses bougies MT5 officielles.`);$("livePrice").textContent=row?fmt(row.price):"—";$("liveChange").textContent=row?`${row.technical_verdict} technique`:`${activeBroker} · attente`;
  const levelValues=verdict!=="ATTENDRE"&&row?.levels?[row.levels.entry,row.levels.sl,row.levels.tp1,row.levels.tp2,row.levels.tp3]:[null,null,null,null,null];$("levels").querySelectorAll("strong").forEach((el,i)=>el.textContent=fmt(levelValues[i]));
  const tech=row?.h1;const metrics=[['Tendance H4',row?.h4?.trendStrong],['H1 ↔ H4',row?.h1?.side&&row?.h1?.side===row?.h4?.side],['BOS / CHoCH',tech&&(tech.bos||tech.choch)],['Liquidité',tech?.sweep],['Order Block',tech?.orderBlock],['Fair Value Gap',tech?.fvg],['Break & Retest',tech?.retest],['Momentum RSI',tech?.momentum]];$("technicalGrid").innerHTML=metrics.map(([label,ok])=>`<div class="metric"><small>${label}</small><strong class="${ok?"ok":"no"}">${ok?"Confirmé":"Non confirmé"}</strong></div>`).join("");
  const confirmations=row?.ai_confirmations||[];const contradictions=row?.ai_contradictions||[];$("checks").innerHTML=[...confirmations.map(text=>`<div class="check"><i></i><span>${escapeHtml(text)}</span></div>`),...contradictions.map(text=>`<div class="check no"><i></i><span>${escapeHtml(text)}</span></div>`)].join("")||'<div class="check no"><i></i><span>Analyse OpenAI récente requise</span></div>';$("signalActions").hidden=!(fresh&&verdict!=="ATTENDRE");drawChart(cls);document.querySelectorAll(".result-card").forEach(card=>card.classList.toggle("selected",card.querySelector("h3")?.textContent===selected));}
function drawChart(cls){const up=cls!=="sell",line=$("chartLine"),fill=$("chartFillPath");const upPath="M0 190 C80 176 120 194 190 148 S330 175 420 102 S560 132 650 72 S790 95 900 34",downPath="M0 40 C90 33 118 76 200 61 S332 118 425 102 S565 178 650 146 S790 213 900 202";line.setAttribute("d",up?upPath:downPath);fill.setAttribute("d",`${up?upPath:downPath} L900 250 L0 250 Z`);line.setAttribute("stroke",cls==="sell"?"#ff6b84":cls==="buy"?"#38e8bb":"#ffd166");}
function setMarketStatus(text,state){$("marketStatus").textContent="";$("marketStatus").append(Object.assign(document.createElement("i"),{}),document.createTextNode(text));$("marketStatus").className=`status-pill ${state}`;}
function setAiStatus(text,state){$("aiStatus").textContent="";$("aiStatus").append(Object.assign(document.createElement("i"),{}),document.createTextNode(text));$("aiStatus").className=`status-pill ${state}`;}
function connectLivePrice(){liveSocket?.close();if(activeBroker!=="Deriv"||!symbols[selected])return;try{const ws=new WebSocket("wss://api.derivws.com/trading/v1/options/ws/public");liveSocket=ws;ws.onopen=()=>ws.send(JSON.stringify({ticks:symbols[selected],subscribe:1,req_id:900}));ws.onmessage=event=>{const msg=JSON.parse(event.data);if(msg.tick?.quote){$("livePrice").textContent=fmt(Number(msg.tick.quote));setMarketStatus("Deriv : Live","live");}};ws.onerror=()=>setMarketStatus("Deriv : flux interrompu","error");}catch{setMarketStatus("Deriv : flux indisponible","error");}}
function currentSignalText(){const row=payload?.markets?.find(item=>item.market===selected);if(!row||row.final_verdict==="ATTENDRE")return"";return [`SERA INDICATOR — SIGNAL IA CONFIRMÉ`,`Indice : ${row.market}`,`Signal : ${row.final_verdict}`,`Confiance : ${row.final_confidence}%`,`Entrée : ${fmt(row.levels?.entry)}`,`Stop Loss : ${fmt(row.levels?.sl)}`,`TP1 : ${fmt(row.levels?.tp1)}`,`TP2 : ${fmt(row.levels?.tp2)}`,`TP3 : ${fmt(row.levels?.tp3)}`,`Analyse : ${new Date(payload.updated_at).toLocaleString("fr-FR")}`,`Modèle : ${row.ai_tier}`,``,`Aide à la décision — aucun gain garanti.`,location.href].join("\n");}
async function copySignal(){const text=currentSignalText();if(!text)return;await navigator.clipboard.writeText(text);$("copySignal").textContent="Copié ✓";setTimeout(()=>$("copySignal").textContent="Copier",1500);}
async function shareSignal(){const text=currentSignalText();if(!text)return;if(navigator.share)await navigator.share({title:"Sera Indicator",text,url:location.href});else await navigator.clipboard.writeText(text);}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}

fillMarketSelect();loadSignals();connectLivePrice();setInterval(()=>loadSignals(false),60000);
